### Create a new board
POST http://localhost:5000/api/gameoflife/boards/create
Content-Type: application/json

{
  "initialState": [
    [1, 0, 0],
    [0, 1, 1],
    [1, 1, 0]
  ]
}

### Get the current state of the board
GET http://localhost:5000/api/gameoflife/boards/1

### Get the next state of the board
GET http://localhost:5000/api/gameoflife/boards/1/next

### Get the state of the board after 3 generations
GET http://localhost:5000/api/gameoflife/boards/1/generations/3

### Get the final state of the board after 5 generations
GET http://localhost:5000/api/gameoflife/boards/1/final?maxGenerations=5