@GameOfLifeAPI_HostAddress = http://localhost:5217


###
# Create a new board using the /create endpoint
POST {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/create
Content-Type: application/json
{
  "initialState": [
    [1, 0, 0],
    [0, 0, 0],
    [0, 0, 1]
  ]
}


###
# Create a new board using the /create endpoint
POST {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/create
Content-Type: application/json

{
  "initialState": [
    [0, 0, 1],
    [1, 1, 1],
    [0, 0, 0]
  ]
}


###
@boardId1 = 1465577487
# Get the next generation of a board
GET {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/{{boardId1}}/next
Accept: application/json


###
@boardId2 = 1760271482
# Get the board
GET {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/{{boardId2}}
Accept: application/json



###
# Get states at a specific generation
@boardId3 = 1760271482
@generations = 3
GET {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/{{boardId3}}/generations/{{generations}}
Accept: application/json

###
# Get the final state of a board
@boardId4 = 893794838
@maxGenerations = 2
GET {{GameOfLifeAPI_HostAddress}}/api/gameoflife/boards/{{boardId4}}/final?maxGenerations={{maxGenerations}}
Accept: application/json